export const ingredientsCategory = {
    'Vegetables' : [
        "Artichoke",
        "Aubergine",
        "Asparagus",
        "Broccoflower",
        "Broccoli",
        "Brussels Sprouts",
        "Cabbage",
        "Kohlrabi",
        "Savoy Cabbage",
        "Red Cabbage",
        "Sour Cabbage",
        "Cauliflower",
        "Celery",
        "Chicory",
        "Cilantro",
        "Dill",
        "Lettuce",
        "Eggplant",
        "Endive",
        "Fiddleheads",
        "Frisee",
        "Fennel",
        "Greens",
        "Beet Greens",
        "Bok Choy",
        "Chard",
        "Collard Greens",
        "Kale",
        "Lettuce",
        "Mustard Greens",
        "Spinach",
        "Alfalfa Sprouts",
        "Azuki Beans",
        "Bean Sprouts",
        "Black Beans",
        "Black-eyed Peas",
        "Borlotti Bean",
        "Broad Beans",
        "Chickpeas",
        "Garbanzos",
        "Ceci Beans",
        "Green Beans",
        "Kidney Beans",
        "Lentils",
        "Lima Beans",
        "Butter Bean",
        "Mung Beans",
        "Navy Beans",
        "Peanuts",
        "Pinto Beans",
        "Runner Beans",
        "Split Peas",
        "Soy Beans",
        "Peas",
        "Mange Tout",
        "Snap Peas",
        "Mushrooms",
        "Nettles",
        "Oca",
        "Okra",
        "Onion Sprouts",
        "Chives",
        "Garlic",
        "Leek",
        "Onion",
        "Shallot",
        "Scallion",
        "Spring Onion",
        "Green Onion",
        "Bell Pepper",
        "Chili Pepper",
        "Jalapeño",
        "Habanero",
        "Paprika",
        "Tabasco Pepper",
        "Cayenne Pepper",
        "Radicchio",
        "Rhubarb",
        "Beetroot",
        "Beet",
        "Mangelwurzel",
        "Carrot",
        "Celeriac",
        "Corms",
        "Eddoe",
        "Konjac",
        "Taro",
        "Water Chestnut",
        "Ginger",
        "Parsnip",
        "Rutabaga",
        "Swede",
        "Radish",
        "Wasabi",
        "Horseradish",
        "Daikon",
        "White Radish",
        "Turnip",
        "Tubers",
        "Jicama",
        "Jerusalem Artichoke",
        "Kumara",
        "Potato",
        "Sour Yam",
        "Sweet Potato",
        "Sweet Yam",
        "Yam",
        "Salsify",
        "Skirret",
        "Succotash",
        "Sweetcorn",
        "Topinambur",
        "Squashes",
        "Acorn Squash",
        "Bitter Melon",
        "Butternut Squash",
        "Banana Squash",
        "Courgette",
        "Zucchini",
        "Cucumber",
        "Delicata",
        "Gem Squash",
        "Hubbard Squash",
        "Marrow",
        "Spaghetti Squash",
        "Tat Soi",
        "Tomatillo",
        "Tomato",
        "Watercress"
      ],
      
    'Fruits' : [
        "Abiu",
        "Açaí",
        "Acerola",
        "Akebi",
        "Ackee",
        "African Cherry Orange",
        "American Mayapple",
        "Apple",
        "Apricot",
        "Aratiles",
        "Araza",
        "Avocado",
        "Banana",
        "Bilberry",
        "Blackberry",
        "Blackcurrant",
        "Black Sapote",
        "Blueberry",
        "Boysenberry",
        "Breadfruit",
        "Buddha's Hand (Fingered Citron)",
        "Cactus Pear",
        "Canistel",
        "Catmon",
        "Cempedak",
        "Cherimoya (Custard Apple)",
        "Cherry",
        "Chico Fruit",
        "Citron",
        "Cloudberry",
        "Coco De Mer",
        "Coconut",
        "Crab Apple",
        "Cranberry",
        "Currant",
        "Damson",
        "Date",
        "Dragonfruit (or Pitaya)",
        "Durian",
        "Elderberry",
        "Feijoa",
        "Fig",
        "Finger Lime (or Caviar Lime)",
        "Gac",
        "Goji Berry",
        "Gooseberry",
        "Grape",
        "Raisin",
        "Grapefruit",
        "Grewia Asiatica",
        "Guava",
        "Hala Fruit",
        "Haws, Fruit of Hawthorn",
        "Honeyberry",
        "Huckleberry",
        "Jabuticaba (Plinia)",
        "Jackfruit",
        "Jambul",
        "Japanese Plum",
        "Jostaberry",
        "Jujube",
        "Juniper Berry",
        "Kaffir Lime",
        "Kiwano (Horned Melon)",
        "Kiwifruit",
        "Kumquat",
        "Lanzones",
        "Lemon",
        "Lime",
        "Loganberry",
        "Longan",
        "Loquat",
        "Lulo",
        "Lychee",
        "Magellan Barberry",
        "Macopa (Wax Apple)",
        "Mamey Apple",
        "Mamey Sapote",
        "Mango",
        "Mangosteen",
        "Marionberry",
        "Medlar",
        "Melon",
        "Cantaloupe",
        "Galia Melon",
        "Honeydew",
        "Mouse Melon",
        "Muskmelon",
        "Watermelon",
        "Miracle Fruit",
        "Momordica Fruit",
        "Monstera Deliciosa",
        "Mulberry",
        "Nance",
        "Nectarine",
        "Orange",
        "Blood Orange",
        "Clementine",
        "Mandarine",
        "Tangerine",
        "Papaya",
        "Passionfruit",
        "Pawpaw",
        "Peach",
        "Pear",
        "Persimmon",
        "Plantain",
        "Plum",
        "Prune (Dried Plum)",
        "Pineapple",
        "Pineberry",
        "Plumcot",
        "Pomegranate",
        "Pomelo",
        "Quince",
        "Raspberry",
        "Salmonberry",
        "Rambutan",
        "Redcurrant",
        "Rose Apple",
        "Salal Berry",
        "Salak",
        "Santol",
        "Sapodilla",
        "Sapote",
        "Sarguelas",
        "Satsuma",
        "Sloe",
        "Soursop",
        "Star Apple",
        "Star Fruit",
        "Strawberry",
        "Sugar Apple",
        "Suriname Cherry",
        "Tamarillo",
        "Tamarind",
        "Tangelo",
        "Tayberry",
        "Thimbleberry",
        "Ugli Fruit",
        "White Currant",
        "White Sapote",
        "Ximenia",
        "Yuzu"
      ],

    'Dairy' : [
        "Milk",
        "Condensed Milk",
        "Scalded Milk",
        "Evaporated Milk",
        "Baked Milk",
        "Dulce De Leche",
        "Malai",
        "Powdered Milk",
        "Khoa",
        "Infant Formula",
        "Whey",
        "Buttermilk",
        "Milk Skin",
        "Cream",
        "Whipped Cream",
        "Single Cream",
        "Double Cream",
        "Clotted Cream",
        "Kaymak",
        "Sour Cream",
        "Smetana",
        "Crème Fraîche",
        "Butter",
        "Ghee",
        "Smen",
        "Anhydrous Milkfat",
        "Kefir",
        "Soured Milk",
        "Cultured Buttermilk",
        "Clabber",
        "Filmjölk",
        "Ymer",
        "Viili",
        "Kumis",
        "Amasi",
        "Mursik",
        "Yogurt",
        "Acidophiline",
        "Matzoon",
        "Skyr",
        "Strained Yogurt",
        "Qatyq",
        "Ryazhenka",
        "Varenets",
        "Ayran",
        "Doogh",
        "Lassi",
        "Leben",
        "Cheese",
        "Cheddar",
        "Grana Cheeses",
        "Gruyère",
        "Blue Cheese",
        "Brined Cheese",
        "Washed-Rind Cheese",
        "Fresh Cheeses",
        "Chhena",
        "Paneer",
        "Cream Cheese",
        "Whey Cheese",
        "Ricotta",
        "Manouri",
        "Anthotyros",
        "Mizithra",
        "Brown Cheese",
        "Custard",
        "Imitation Custard",
        "Ice Cream",
        "Gelato",
        "Ice Milk",
        "Frozen Custard",
        "Frozen Yogurt",
        "Casein",
        "Caseinates",
        "Milk Protein Concentrates",
        "Whey Protein Concentrates",
        "Hydrolysates",
        "Mineral Concentrates"
      ],
    
      'Baking Needs' : [
        // Flour
        "Flour",
        "All-Purpose Flour",
        "Gluten-Free Flour",
        "Whole Wheat Flour",
        "Whole Grain Flour",
        "Bread Flour",
        "Cake Flour",
        "Pastry Flour",
        "Self-Rising Flour",
        "Cornmeal",
        "Cornstarch",
        
        // Leaveners
        "Eggs",
        "Yeast",
        "Baking Powder",
        "Baking Soda",
        
        // Sugar
        "Granulated Sugar",
        "Confectioners' Sugar",
        "Powdered Sugar",
        "Brown Sugar",
        "Superfine Sugar",
        "Sanding Sugar",
        "Date Sugar",
        "Coconut Sugar",
        "Maple Sugar",
        "Honey",
        "Molasses",
        "Maple Syrup",
        "Cane Syrup",
        "Agave Syrup",
        
        // Salt
        "Table Salt",
        "Sea Salt",
        
        // Dairy
        "Unsalted Butter",
        "Large Eggs",
        "Milk",
        "Buttermilk",
        "Alternative Milks",
        "Cream Cheese",
        "Sour Cream",
        
        // Fats: Oil and Shortening
        "Vegetable Oil",
        "Butter",
        "Shortening",
        
        // Extracts and Flavorings
        "Pure Vanilla Extract",
        "Almond Extract",
        "Lemon Extract",
        "Mint Extract",
        "Rum Flavoring",
        "Brandy Flavoring",
        "Whole Vanilla Bean",
        
        // Spices
        "Ground Cinnamon",
        "Ground Cloves",
        "Allspice",
        "Ginger",
        "Nutmeg",
        "Whole Spices",
        
        // Add-Ins
        "Bar Chocolate",
        "Chocolate Chips",
        "Unsweetened Cocoa Powder",
        "Dutch-Process Cocoa Powder",
        "Dried Fruits",
        "Raisins",
        "Cranberries",
        "Rolled Oats",
        "Nuts",
        "Jams",
        "Jellies",
        "Fruit Preserves",
        "Peanut Butter",
        "Almond Butter",
        "Food Coloring",
        "Sprinkles",
        "Crystalized Ginger",
        "Matcha Powder",
        "Chia Seeds",
        "Shredded Coconut",
        "Flaked Coconut",
        "Digestive Biscuits"
      ],

    "Poultry" : [
        // Red Meats
        "Beef",
        "Pork",
        "Lamb",
        "Mutton",
        "Venison",
        "Goat",
        "Buffalo",
        "Elk",
        
        // White Meats
        "Chicken",
        "Turkey",
        "Veal",
        "Duck",
        "Rabbit",
        "Goose",
        "Pheasant",
        "Quail",
        
        // Cuts of Beef
        "Sirloin",
        "Tenderloin",
        "Ribeye",
        "Brisket",
        "T-Bone",
        "Chuck",
        "Round",
        "Shank",
        
        // Cuts of Chicken
        "Chicken Breast",
        "Chicken Thigh",
        "Chicken Wing",
        "Chicken Drumstick",
        "Chicken Tender",
        "Chicken Leg",
        "Chicken Back",
        "Chicken Giblets",
        
 
      ],
    
    "Seafood" : [
        "Fish",
        "Shellfish",
        "Crustaceans",
        "Barnacles (Austromegabalanus psittacus)",
        "Crabs",
        "Craw/Crayfish",
        "Lobsters",
        "Shrimps/Prawns",
        "Mollusca",
        "Abalone",
        "Cockle",
        "Clam",
        "Loco",
        "Mussel",
        "Oyster",
        "Periwinkle",
        "Scallop (see also bay scallop and sea scallop)",
        "Conch (Snails)",
        "Cephalopods",
        "Cuttlefish",
        "Octopus",
        "Nautilus",
        "Squid",
        "Echinoderms",
        "Sea cucumber",
        "Uni (sea urchin 'roe')"
      ],
    
    'Other': 
        []
  };