const staticSubstitutions = {
  "milk": ["almond milk", "soy milk", "oat milk", "rice milk", "coconut milk"],
  "egg": ["flaxseed meal", "chia seeds", "applesauce", "mashed banana", "yogurt"],
  "butter": ["margarine", "coconut oil", "olive oil", "avocado", "applesauce"],
  "sugar": ["honey", "maple syrup", "agave nectar", "stevia", "coconut sugar"],
  "flour": ["almond flour", "coconut flour", "oat flour", "rice flour", "quinoa flour"],
  "cream": ["coconut cream", "cashew cream", "silken tofu", "greek yogurt"],
  "bread crumbs": ["crushed cornflakes", "crushed crackers", "oatmeal", "panko"],
  "soy sauce": ["tamari", "coconut aminos", "worcestershire sauce", "miso paste"],
  "heavy cream": ["evaporated milk", "half-and-half", "coconut milk", "cashew cream"],
  "mayonnaise": ["greek yogurt", "sour cream", "hummus", "mashed avocado"],
  "lemon juice": ["lime juice", "vinegar", "citric acid", "white wine"],
  "baking powder": ["baking soda and cream of tartar", "yeast", "club soda"],
  "cornstarch": ["arrowroot powder", "tapioca flour", "potato starch", "rice flour"],
  "brown sugar": ["white sugar with molasses", "coconut sugar", "maple syrup"],
  "vanilla extract": ["vanilla bean", "vanilla paste", "almond extract"],
  "chicken broth": ["vegetable broth", "beef broth", "water with bouillon cubes"],
  "tomato sauce": ["tomato paste with water", "pureed tomatoes", "ketchup"],
  "olive oil": ["vegetable oil", "canola oil", "coconut oil", "butter"],
  "soy milk": ["almond milk", "oat milk", "rice milk", "coconut milk"],
  "rice": ["quinoa", "barley", "cauliflower rice", "farro"],
  "potato": ["sweet potato", "turnip", "parsnip", "rutabaga"],
  "yogurt": ["sour cream", "cottage cheese", "kefir", "buttermilk"],
  "apple cider vinegar": ["white vinegar", "lemon juice", "lime juice", "rice vinegar"],
  "balsamic vinegar": ["red wine vinegar", "sherry vinegar", "apple cider vinegar"],
  "maple syrup": ["honey", "agave nectar", "corn syrup", "molasses"],
  "molasses": ["honey", "maple syrup", "brown sugar", "corn syrup"],
  "mustard": ["dijon mustard", "spicy brown mustard", "horseradish", "wasabi"],
  "ketchup": ["tomato paste", "tomato sauce", "barbecue sauce", "salsa"],
  "sour cream": ["greek yogurt", "cottage cheese", "cream cheese", "buttermilk"],
  "cream cheese": ["ricotta cheese", "mascarpone", "greek yogurt", "sour cream"],
  "whipping cream": ["half-and-half", "evaporated milk", "coconut cream", "silken tofu"],
  "parmesan cheese": ["asiago cheese", "pecorino romano", "grana padano", "nutritional yeast"],
  "cheddar cheese": ["colby cheese", "monterey jack", "american cheese", "gouda"],
  "mozzarella cheese": ["provolone", "fontina", "munster", "ricotta"],
  "cottage cheese": ["ricotta cheese", "greek yogurt", "silken tofu", "mashed avocado"],
  "honey": ["maple syrup", "agave nectar", "molasses", "corn syrup"],
  "fish sauce": ["soy sauce", "tamari", "worcestershire sauce", "anchovy paste"],
  "red wine": ["white wine", "balsamic vinegar", "apple cider vinegar", "pomegranate juice"],
  "white wine": ["vermouth", "chicken broth", "apple cider vinegar", "white grape juice"],
  "beer": ["chicken broth", "beef broth", "vegetable broth", "apple cider"],
  "bourbon": ["scotch", "brandy", "rum", "whiskey"],
  "rum": ["brandy", "whiskey", "bourbon", "cognac"],
  "vodka": ["gin", "white rum", "tequila", "white wine"],
  "cognac": ["brandy", "rum", "bourbon", "whiskey"],
  "tequila": ["mezcal", "white rum", "vodka", "gin"],
  "whiskey": ["bourbon", "scotch", "rum", "brandy"],
  "yeast": ["baking powder", "baking soda and cream of tartar", "club soda"],
  "panko": ["bread crumbs", "crushed cornflakes", "crushed crackers", "oatmeal"],
  "crushed tomatoes": ["tomato sauce", "pureed tomatoes", "diced tomatoes", "tomato paste with water"],
  "evaporated milk": ["half-and-half", "heavy cream", "coconut milk", "cashew cream"],
  "condensed milk": ["evaporated milk with sugar", "heavy cream with sugar", "coconut milk with sugar"],
  "coconut milk": ["almond milk", "soy milk", "oat milk", "rice milk"],
  "coconut oil": ["vegetable oil", "canola oil", "olive oil", "butter"],
  "vegetable oil": ["canola oil", "olive oil", "coconut oil", "butter"],
  "canola oil": ["vegetable oil", "olive oil", "coconut oil", "butter"],
  "tahini": ["peanut butter", "almond butter", "sunflower seed butter", "cashew butter"],
  "peanut butter": ["almond butter", "cashew butter", "sunflower seed butter", "tahini"],
  "almond butter": ["peanut butter", "cashew butter", "sunflower seed butter", "tahini"],
  "cashew butter": ["peanut butter", "almond butter", "sunflower seed butter", "tahini"],
  "sunflower seed butter": ["peanut butter", "almond butter", "cashew butter", "tahini"],
  "ricotta cheese": ["cottage cheese", "cream cheese", "greek yogurt", "silken tofu"],
  "tofu": ["tempeh", "seitan", "chickpeas", "black beans"],
  "tempeh": ["tofu", "seitan", "chickpeas", "black beans"],
  "seitan": ["tofu", "tempeh", "chickpeas", "black beans"],
  "chickpeas": ["black beans", "white beans", "lentils", "kidney beans"],
  "black beans": ["chickpeas", "white beans", "lentils", "kidney beans"],
  "white beans": ["chickpeas", "black beans", "lentils", "kidney beans"],
  "lentils": ["chickpeas", "black beans", "white beans", "kidney beans"],
  "kidney beans": ["chickpeas", "black beans", "white beans", "lentils"],
  "quinoa": ["rice", "barley", "bulgur", "farro"],
  "barley": ["rice", "quinoa", "bulgur", "farro"],
  "bulgur": ["rice", "quinoa", "barley", "farro"],
  "farro": ["rice", "quinoa", "barley", "bulgur"],
  "cauliflower rice": ["rice", "quinoa", "barley", "bulgur"],
  "cornmeal": ["polenta", "semolina", "corn grits", "masa harina"],
  "polenta": ["cornmeal", "semolina", "corn grits", "masa harina"],
  "semolina": ["cornmeal", "polenta", "corn grits", "masa harina"],
  "corn grits": ["cornmeal", "polenta", "semolina", "masa harina"],
  "masa harina": ["cornmeal", "polenta", "semolina", "corn grits"],
  "arugula": ["spinach", "kale", "watercress", "mustard greens"],
  "spinach": ["arugula", "kale", "watercress", "mustard greens"],
  "kale": ["arugula", "spinach", "watercress", "mustard greens"],
  "watercress": ["arugula", "spinach", "kale", "mustard greens"],
  "mustard greens": ["arugula", "spinach", "kale", "watercress"],
  "zucchini": ["yellow squash", "cucumber", "eggplant", "bell pepper"],
  "yellow squash": ["zucchini", "cucumber", "eggplant", "bell pepper"],
  "cucumber": ["zucchini", "yellow squash", "eggplant", "bell pepper"],
  "eggplant": ["zucchini", "yellow squash", "cucumber", "bell pepper"],
  "bell pepper": ["zucchini", "yellow squash", "cucumber", "eggplant"],
  "carrot": ["parsnip", "sweet potato", "butternut squash", "pumpkin"],
  "parsnip": ["carrot", "sweet potato", "butternut squash", "pumpkin"],
  "sweet potato": ["carrot", "parsnip", "butternut squash", "pumpkin"],
  "butternut squash": ["carrot", "parsnip", "sweet potato", "pumpkin"],
  "pumpkin": ["carrot", "parsnip", "sweet potato", "butternut squash"],
  "broccoli": ["cauliflower", "brussels sprouts", "asparagus", "green beans"],
  "cauliflower": ["broccoli", "brussels sprouts", "asparagus", "green beans"],
  "brussels sprouts": ["broccoli", "cauliflower", "asparagus", "green beans"],
  "asparagus": ["broccoli", "cauliflower", "brussels sprouts", "green beans"],
  "green beans": ["broccoli", "cauliflower", "brussels sprouts", "asparagus"],
  "mushroom": ["eggplant", "zucchini", "bell pepper", "tofu"],
  "tofu": ["tempeh", "seitan", "chickpeas", "black beans"],
  "tempeh": ["tofu", "seitan", "chickpeas", "black beans"],
  "seitan": ["tofu", "tempeh", "chickpeas", "black beans"],
  "chickpeas": ["black beans", "white beans", "lentils", "kidney beans"],
  "black beans": ["chickpeas", "white beans", "lentils", "kidney beans"],
  "white beans": ["chickpeas", "black beans", "lentils", "kidney beans"],
  "lentils": ["chickpeas", "black beans", "white beans", "kidney beans"],
  "kidney beans": ["chickpeas", "black beans", "white beans", "lentils"],
  "quinoa": ["rice", "barley", "bulgur", "farro"],
  "barley": ["rice", "quinoa", "bulgur", "farro"],
  "bulgur": ["rice", "quinoa", "barley", "farro"],
  "farro": ["rice", "quinoa", "barley", "bulgur"],
  "cauliflower rice": ["rice", "quinoa", "barley", "bulgur"],
  "cornmeal": ["polenta", "semolina", "corn grits", "masa harina"],
  "polenta": ["cornmeal", "semolina", "corn grits", "masa harina"],
  "semolina": ["cornmeal", "polenta", "corn grits", "masa harina"],
  "corn grits": ["cornmeal", "polenta", "semolina", "masa harina"],
  "masa harina": ["cornmeal", "polenta", "semolina", "corn grits"],
  "arugula": ["spinach", "kale", "watercress", "mustard greens"],
  "spinach": ["arugula", "kale", "watercress", "mustard greens"],
  "kale": ["arugula", "spinach", "watercress", "mustard greens"],
  "watercress": ["arugula", "spinach", "kale", "mustard greens"],
  "mustard greens": ["arugula", "spinach", "kale", "watercress"],
  "zucchini": ["yellow squash", "cucumber", "eggplant", "bell pepper"],
  "yellow squash": ["zucchini", "cucumber", "eggplant", "bell pepper"],
  "cucumber": ["zucchini", "yellow squash", "eggplant", "bell pepper"],
  "eggplant": ["zucchini", "yellow squash", "cucumber", "bell pepper"],
  "bell pepper": ["zucchini", "yellow squash", "cucumber", "eggplant"],
  "carrot": ["parsnip", "sweet potato", "butternut squash", "pumpkin"],
  "parsnip": ["carrot", "sweet potato", "butternut squash", "pumpkin"],
  "sweet potato": ["carrot", "parsnip", "butternut squash", "pumpkin"],
  "butternut squash": ["carrot", "parsnip", "sweet potato", "pumpkin"],
  "pumpkin": ["carrot", "parsnip", "sweet potato", "butternut squash"],
  "broccoli": ["cauliflower", "brussels sprouts", "asparagus", "green beans"],
  "cauliflower": ["broccoli", "brussels sprouts", "asparagus", "green beans"],
  "brussels sprouts": ["broccoli", "cauliflower", "asparagus", "green beans"],
  "asparagus": ["broccoli", "cauliflower", "brussels sprouts", "green beans"],
  "green beans": ["broccoli", "cauliflower", "brussels sprouts", "asparagus"],
  "mushroom": ["eggplant", "zucchini", "bell pepper", "tofu"],
  "basil": ["oregano", "thyme", "parsley", "cilantro"],
  "cilantro": ["parsley", "basil", "mint", "dill"],
  "parsley": ["cilantro", "basil", "mint", "oregano"],
  "oregano": ["basil", "thyme", "marjoram", "parsley"],
  "thyme": ["oregano", "basil", "marjoram", "rosemary"],
  "rosemary": ["thyme", "oregano", "sage", "basil"],
  "sage": ["rosemary", "thyme", "marjoram", "oregano"],
  "dill": ["fennel fronds", "tarragon", "parsley", "cilantro"],
  "tarragon": ["dill", "fennel fronds", "parsley", "basil"],
  "mint": ["basil", "cilantro", "parsley", "dill"],
  "nutmeg": ["allspice", "cinnamon", "ginger", "cloves"],
  "allspice": ["cinnamon", "nutmeg", "cloves", "ginger"],
  "cloves": ["allspice", "nutmeg", "cinnamon", "ginger"],
  "ginger": ["allspice", "nutmeg", "cinnamon", "cloves"],
  "paprika": ["cayenne pepper", "chili powder", "smoked paprika", "ancho chili powder"],
  "cayenne pepper": ["paprika", "chili powder", "red pepper flakes", "ancho chili powder"],
  "chili powder": ["paprika", "cayenne pepper", "ancho chili powder", "chipotle powder"],
  "smoked paprika": ["paprika", "ancho chili powder", "chipotle powder", "cayenne pepper"],
  "cumin": ["coriander", "chili powder", "paprika", "curry powder"],
  "coriander": ["cumin", "chili powder", "paprika", "curry powder"],
  "fennel seeds": ["anise seeds", "caraway seeds", "dill seeds", "cumin seeds"],
  "caraway seeds": ["fennel seeds", "anise seeds", "dill seeds", "cumin seeds"],
  "dill seeds": ["fennel seeds", "anise seeds", "caraway seeds", "cumin seeds"],
  "anise seeds": ["fennel seeds", "caraway seeds", "dill seeds", "cumin seeds"],
  "saffron": ["turmeric", "annatto", "paprika", "curry powder"],
  "turmeric": ["saffron", "annatto", "paprika", "curry powder"],
  "curry powder": ["garam masala", "chili powder", "paprika", "cumin"],
  "garam masala": ["curry powder", "chili powder", "paprika", "cumin"],
  "bay leaves": ["thyme", "oregano", "rosemary", "basil"],
  "cardamom": ["cinnamon", "nutmeg", "cloves", "allspice"],
  "cinnamon": ["nutmeg", "cloves", "allspice", "cardamom"],
  "chives": ["green onions", "scallions", "leeks", "shallots"],
  "green onions": ["chives", "scallions", "leeks", "shallots"],
  "scallions": ["chives", "green onions", "leeks", "shallots"],
  "leeks": ["chives", "green onions", "scallions", "shallots"],
  "shallots": ["chives", "green onions", "scallions", "leeks"],
  "garlic": ["shallots", "onion powder", "garlic powder", "leeks"],
  "onion powder": ["garlic powder", "shallots", "leeks", "chives"],
  "garlic powder": ["onion powder", "shallots", "leeks", "chives"],
  "tomato paste": ["tomato sauce", "ketchup", "pureed tomatoes", "crushed tomatoes"],
  "crushed tomatoes": ["tomato paste", "tomato sauce", "pureed tomatoes", "diced tomatoes"],
  "diced tomatoes": ["crushed tomatoes", "tomato paste", "tomato sauce", "pureed tomatoes"],
  "tomato sauce": ["tomato paste", "crushed tomatoes", "pureed tomatoes", "diced tomatoes"],
  "brown rice": ["quinoa", "barley", "bulgur", "farro"],
  "whole wheat flour": ["all-purpose flour", "almond flour", "coconut flour", "oat flour"],
  "all-purpose flour": ["whole wheat flour", "almond flour", "coconut flour", "oat flour"],
  "sour cream": ["yogurt", "cream cheese", "cottage cheese", "buttermilk"],
  "cream cheese": ["yogurt", "cottage cheese", "ricotta cheese", "mascarpone"],
  "yogurt": ["sour cream", "cream cheese", "cottage cheese", "ricotta cheese"],
  "ricotta cheese": ["cottage cheese", "cream cheese", "yogurt", "mascarpone"],
  "buttermilk": ["sour cream", "yogurt", "cream cheese", "cottage cheese"],
  "half-and-half": ["heavy cream", "evaporated milk", "whole milk", "coconut cream"],
  "whole milk": ["half-and-half", "heavy cream", "evaporated milk", "coconut milk"],
  "cheddar cheese": ["colby cheese", "monterey jack", "american cheese", "gouda"],
  "colby cheese": ["cheddar cheese", "monterey jack", "american cheese", "gouda"],
  "monterey jack": ["cheddar cheese", "colby cheese", "american cheese", "gouda"],
  "american cheese": ["cheddar cheese", "colby cheese", "monterey jack", "gouda"],
  "gouda": ["cheddar cheese", "colby cheese", "monterey jack", "american cheese"],
  "blue cheese": ["gorgonzola", "roquefort", "stilton", "feta"],
  "feta cheese": ["blue cheese", "gorgonzola", "roquefort", "stilton"],
  "gorgonzola": ["blue cheese", "feta cheese", "roquefort", "stilton"],
  "roquefort": ["blue cheese", "feta cheese", "gorgonzola", "stilton"],
  "stilton": ["blue cheese", "feta cheese", "gorgonzola", "roquefort"],
  "chocolate chips": ["carob chips", "cocoa nibs", "chopped chocolate", "dark chocolate chips"],
  "dark chocolate chips": ["chocolate chips", "carob chips", "cocoa nibs", "chopped chocolate"],
  "cocoa powder": ["carob powder", "chocolate chips", "chopped chocolate", "dark chocolate chips"],
  "carob powder": ["cocoa powder", "chocolate chips", "chopped chocolate", "dark chocolate chips"],
  "peanut butter": ["almond butter", "cashew butter", "sunflower seed butter", "tahini"],
  "almond butter": ["peanut butter", "cashew butter", "sunflower seed butter", "tahini"],
  "cashew butter": ["peanut butter", "almond butter", "sunflower seed butter", "tahini"],
  "sunflower seed butter": ["peanut butter", "almond butter", "cashew butter", "tahini"],
  "hazelnuts": ["almonds", "walnuts", "pecans", "macadamia nuts"],
  "almonds": ["hazelnuts", "walnuts", "pecans", "macadamia nuts"],
  "walnuts": ["hazelnuts", "almonds", "pecans", "macadamia nuts"],
  "pecans": ["hazelnuts", "almonds", "walnuts", "macadamia nuts"],
  "macadamia nuts": ["hazelnuts", "almonds", "walnuts", "pecans"],
  "cashews": ["peanuts", "almonds", "walnuts", "pecans"],
  "peanuts": ["cashews", "almonds", "walnuts", "pecans"],
  "pistachios": ["cashews", "almonds", "walnuts", "pecans"],
  "pine nuts": ["cashews", "almonds", "walnuts", "pecans"],
  "coconut flakes": ["shredded coconut", "desiccated coconut", "coconut milk", "coconut cream"],
  "shredded coconut": ["coconut flakes", "desiccated coconut", "coconut milk", "coconut cream"],
  "desiccated coconut": ["coconut flakes", "shredded coconut", "coconut milk", "coconut cream"],
  "coconut milk": ["coconut flakes", "shredded coconut", "desiccated coconut", "coconut cream"],
  "coconut cream": ["coconut flakes", "shredded coconut", "desiccated coconut", "coconut milk"],
  "pumpkin seeds": ["sunflower seeds", "chia seeds", "flaxseeds", "hemp seeds"],
  "sunflower seeds": ["pumpkin seeds", "chia seeds", "flaxseeds", "hemp seeds"],
  "chia seeds": ["pumpkin seeds", "sunflower seeds", "flaxseeds", "hemp seeds"],
  "flaxseeds": ["pumpkin seeds", "sunflower seeds", "chia seeds", "hemp seeds"],
  "hemp seeds": ["pumpkin seeds", "sunflower seeds", "chia seeds", "flaxseeds"],
  "canned beans": ["dried beans", "chickpeas", "lentils", "black beans"],
  "dried beans": ["canned beans", "chickpeas", "lentils", "black beans"],
  "canned corn": ["frozen corn", "fresh corn", "cornmeal", "polenta"],
  "frozen corn": ["canned corn", "fresh corn", "cornmeal", "polenta"],
  "fresh corn": ["canned corn", "frozen corn", "cornmeal", "polenta"],
  "canned tomatoes": ["fresh tomatoes", "tomato sauce", "tomato paste", "crushed tomatoes"],
  "fresh tomatoes": ["canned tomatoes", "tomato sauce", "tomato paste", "crushed tomatoes"],
  "pasta": ["zucchini noodles", "spaghetti squash", "quinoa", "rice"],
  "zucchini noodles": ["pasta", "spaghetti squash", "quinoa", "rice"],
  "spaghetti squash": ["pasta", "zucchini noodles", "quinoa", "rice"],
  "couscous": ["quinoa", "bulgur", "farro", "rice"],
  "quinoa": ["couscous", "bulgur", "farro", "rice"],
  "bulgur": ["couscous", "quinoa", "farro", "rice"],
  "farro": ["couscous", "quinoa", "bulgur", "rice"],
  "rice": ["quinoa", "couscous", "bulgur", "farro"],
  "coconut milk": ["almond milk", "soy milk", "oat milk", "rice milk"],
  "coconut cream": ["coconut milk", "almond milk", "soy milk", "oat milk"],
  "almond milk": ["coconut milk", "soy milk", "oat milk", "rice milk"],
  "soy milk": ["coconut milk", "almond milk", "oat milk", "rice milk"],
  "oat milk": ["coconut milk", "almond milk", "soy milk", "rice milk"],
  "rice milk": ["coconut milk", "almond milk", "soy milk", "oat milk"],
  "avocado": ["mashed banana", "greek yogurt", "applesauce", "silken tofu"],
  "mashed banana": ["avocado", "greek yogurt", "applesauce", "silken tofu"],
  "greek yogurt": ["avocado", "mashed banana", "applesauce", "silken tofu"],
  "applesauce": ["avocado", "mashed banana", "greek yogurt", "silken tofu"],
  "silken tofu": ["avocado", "mashed banana", "greek yogurt", "applesauce"],
  "blackstrap molasses": ["regular molasses", "dark corn syrup", "maple syrup", "honey"],
  "regular molasses": ["blackstrap molasses", "dark corn syrup", "maple syrup", "honey"],
  "dark corn syrup": ["blackstrap molasses", "regular molasses", "maple syrup", "honey"],
  "maple syrup": ["blackstrap molasses", "regular molasses", "dark corn syrup", "honey"],
  "honey": ["blackstrap molasses", "regular molasses", "dark corn syrup", "maple syrup"],
  "sweetened condensed milk": ["evaporated milk with sugar", "heavy cream with sugar", "coconut milk with sugar"],
  "evaporated milk with sugar": ["sweetened condensed milk", "heavy cream with sugar", "coconut milk with sugar"],
  "heavy cream with sugar": ["sweetened condensed milk", "evaporated milk with sugar", "coconut milk with sugar"],
  "coconut milk with sugar": ["sweetened condensed milk", "evaporated milk with sugar", "heavy cream with sugar"],
  "blackstrap molasses": ["regular molasses", "dark corn syrup", "maple syrup", "honey"],
  "regular molasses": ["blackstrap molasses", "dark corn syrup", "maple syrup", "honey"],
  "dark corn syrup": ["blackstrap molasses", "regular molasses", "maple syrup", "honey"],
  "maple syrup": ["blackstrap molasses", "regular molasses", "dark corn syrup", "honey"],
  "honey": ["blackstrap molasses", "regular molasses", "dark corn syrup", "maple syrup"],
  "molasses": ["honey", "maple syrup", "brown sugar", "corn syrup"],
  "brown sugar": ["white sugar with molasses", "coconut sugar", "maple syrup", "molasses"],
  "white sugar": ["brown sugar", "coconut sugar", "maple syrup", "molasses"],
  "coconut sugar": ["brown sugar", "white sugar with molasses", "maple syrup", "molasses"],
  "maple syrup": ["brown sugar", "white sugar with molasses", "coconut sugar", "molasses"],
  "agave nectar": ["honey", "maple syrup", "corn syrup", "molasses"],
  "corn syrup": ["honey", "maple syrup", "agave nectar", "molasses"],
  "honey": ["agave nectar", "maple syrup", "corn syrup", "molasses"],
  "maple syrup": ["agave nectar", "honey", "corn syrup", "molasses"],
  "molasses": ["agave nectar", "honey", "maple syrup", "corn syrup"],
  "sugar": ["honey", "maple syrup", "agave nectar", "stevia", "coconut sugar"],
  "honey": ["sugar", "maple syrup", "agave nectar", "stevia", "coconut sugar"],
  "maple syrup": ["sugar", "honey", "agave nectar", "stevia", "coconut sugar"],
  "agave nectar": ["sugar", "honey", "maple syrup", "stevia", "coconut sugar"],
  "stevia": ["sugar", "honey", "maple syrup", "agave nectar", "coconut sugar"],
  "coconut sugar": ["sugar", "honey", "maple syrup", "agave nectar", "stevia"],
  "brown rice syrup": ["honey", "maple syrup", "corn syrup", "agave nectar"],
  "honey": ["brown rice syrup", "maple syrup", "corn syrup", "agave nectar"],
  "maple syrup": ["brown rice syrup", "honey", "corn syrup", "agave nectar"],
  "corn syrup": ["brown rice syrup", "honey", "maple syrup", "agave nectar"],
  "agave nectar": ["brown rice syrup", "honey", "maple syrup", "corn syrup"],
  "molasses": ["brown rice syrup", "honey", "maple syrup", "corn syrup"],
  "brown rice syrup": ["molasses", "honey", "maple syrup", "corn syrup"],
  "maple syrup": ["molasses", "honey", "brown rice syrup", "corn syrup"],
  "honey": ["molasses", "maple syrup", "brown rice syrup", "corn syrup"],
  "corn syrup": ["molasses", "honey", "brown rice syrup", "maple syrup"],
  "brown sugar": ["white sugar with molasses", "coconut sugar", "maple syrup", "molasses"],
  "white sugar": ["brown sugar", "coconut sugar", "maple syrup", "molasses"],
  "coconut sugar": ["brown sugar", "white sugar with molasses", "maple syrup", "molasses"],
  "maple syrup": ["brown sugar", "white sugar with molasses", "coconut sugar", "molasses"],
  "agave nectar": ["honey", "maple syrup", "corn syrup", "molasses"],
  "corn syrup": ["honey", "maple syrup", "agave nectar", "molasses"],
  "honey": ["agave nectar", "maple syrup", "corn syrup", "molasses"],
  "maple syrup": ["agave nectar", "honey", "corn syrup", "molasses"],
  "molasses": ["agave nectar", "honey", "maple syrup", "corn syrup"],
  "sugar": ["honey", "maple syrup", "agave nectar", "stevia", "coconut sugar"],
  "honey": ["sugar", "maple syrup", "agave nectar", "stevia", "coconut sugar"],
  "maple syrup": ["sugar", "honey", "agave nectar", "stevia", "coconut sugar"],
  "agave nectar": ["sugar", "honey", "maple syrup", "stevia", "coconut sugar"],
  "stevia": ["sugar", "honey", "maple syrup", "agave nectar", "coconut sugar"],
  "coconut sugar": ["sugar", "honey", "maple syrup", "agave nectar", "stevia"],
  "brown rice syrup": ["honey", "maple syrup", "corn syrup", "agave nectar"],
  "honey": ["brown rice syrup", "maple syrup", "corn syrup", "agave nectar"],
  "maple syrup": ["brown rice syrup", "honey", "corn syrup", "agave nectar"],
  "corn syrup": ["brown rice syrup", "honey", "maple syrup", "agave nectar"],
  "agave nectar": ["brown rice syrup", "honey", "maple syrup", "corn syrup"],
  "molasses": ["brown rice syrup", "honey", "maple syrup", "corn syrup"],
  "brown rice syrup": ["molasses", "honey", "maple syrup", "corn syrup"],
  "maple syrup": ["molasses", "honey", "brown rice syrup", "corn syrup"],
  "honey": ["molasses", "maple syrup", "brown rice syrup", "corn syrup"],
  "corn syrup": ["molasses", "honey", "brown rice syrup", "maple syrup"],
};

export default staticSubstitutions;
