// substitutions.js

const staticSubstitutions = {
    "milk": ["almond milk", "soy milk", "oat milk", "rice milk", "coconut milk"],
    "egg": ["flaxseed meal", "chia seeds", "applesauce", "mashed banana", "yogurt"],
    "butter": ["margarine", "coconut oil", "olive oil", "avocado", "applesauce"],
    "sugar": ["honey", "maple syrup", "agave nectar", "stevia", "coconut sugar"],
    "flour": ["almond flour", "coconut flour", "oat flour", "rice flour", "quinoa flour"],
    "cream": ["coconut cream", "cashew cream", "silken tofu", "greek yogurt"],
    "bread crumbs": ["crushed cornflakes", "crushed crackers", "oatmeal", "panko"],
    "soy sauce": ["tamari", "coconut aminos", "worcestershire sauce", "miso paste"],
    "heavy cream": ["evaporated milk", "half-and-half", "coconut milk", "cashew cream"],
    "mayonnaise": ["greek yogurt", "sour cream", "hummus", "mashed avocado"],
    "lemon juice": ["lime juice", "vinegar", "citric acid", "white wine"],
    "baking powder": ["baking soda and cream of tartar", "yeast", "club soda"],
    "cornstarch": ["arrowroot powder", "tapioca flour", "potato starch", "rice flour"],
    "brown sugar": ["white sugar with molasses", "coconut sugar", "maple syrup"],
    "vanilla extract": ["vanilla bean", "vanilla paste", "almond extract"],
    "chicken broth": ["vegetable broth", "beef broth", "water with bouillon cubes"],
    "tomato sauce": ["tomato paste with water", "pureed tomatoes", "ketchup"],
    "olive oil": ["vegetable oil", "canola oil", "coconut oil", "butter"],
    "soy milk": ["almond milk", "oat milk", "rice milk", "coconut milk"],
    "rice": ["quinoa", "barley", "cauliflower rice", "farro"],
    "potato": ["sweet potato", "turnip", "parsnip", "rutabaga"],
    "yogurt": ["sour cream", "cottage cheese", "kefir", "buttermilk"],
    "apple cider vinegar": ["white vinegar", "lemon juice", "lime juice", "rice vinegar"],
    "balsamic vinegar": ["red wine vinegar", "sherry vinegar", "apple cider vinegar"],
    "maple syrup": ["honey", "agave nectar", "corn syrup", "molasses"],
    "molasses": ["honey", "maple syrup", "brown sugar", "corn syrup"],
    "mustard": ["dijon mustard", "spicy brown mustard", "horseradish", "wasabi"],
    "ketchup": ["tomato paste", "tomato sauce", "barbecue sauce", "salsa"],
    "sour cream": ["greek yogurt", "cottage cheese", "cream cheese", "buttermilk"],
    "cream cheese": ["ricotta cheese", "mascarpone", "greek yogurt", "sour cream"],
    "whipping cream": ["half-and-half", "evaporated milk", "coconut cream", "silken tofu"],
    "parmesan cheese": ["asiago cheese", "pecorino romano", "grana padano", "nutritional yeast"],
    "cheddar cheese": ["colby cheese", "monterey jack", "american cheese", "gouda"],
    "mozzarella cheese": ["provolone", "fontina", "munster", "ricotta"],
    "cottage cheese": ["ricotta cheese", "greek yogurt", "silken tofu", "mashed avocado"],
    "honey": ["maple syrup", "agave nectar", "molasses", "corn syrup"],
    "fish sauce": ["soy sauce", "tamari", "worcestershire sauce", "anchovy paste"],
    "red wine": ["white wine", "balsamic vinegar", "apple cider vinegar", "pomegranate juice"],
    "white wine": ["vermouth", "chicken broth", "apple cider vinegar", "white grape juice"],
    "beer": ["chicken broth", "beef broth", "vegetable broth", "apple cider"],
    "bourbon": ["scotch", "brandy", "rum", "whiskey"],
    "rum": ["brandy", "whiskey", "bourbon", "cognac"],
    "vodka": ["gin", "white rum", "tequila", "white wine"],
    "cognac": ["brandy", "rum", "bourbon", "whiskey"],
    "tequila": ["mezcal", "white rum", "vodka", "gin"],
    "whiskey": ["bourbon", "scotch", "rum", "brandy"],
    "yeast": ["baking powder", "baking soda and cream of tartar", "club soda"],
    "panko": ["bread crumbs", "crushed cornflakes", "crushed crackers", "oatmeal"],
    "crushed tomatoes": ["tomato sauce", "pureed tomatoes", "diced tomatoes", "tomato paste with water"],
    "evaporated milk": ["half-and-half", "heavy cream", "coconut milk", "cashew cream"],
    "condensed milk": ["evaporated milk with sugar", "heavy cream with sugar", "coconut milk with sugar"],
    "coconut milk": ["almond milk", "soy milk", "oat milk", "rice milk"],
    "coconut oil": ["vegetable oil", "canola oil", "olive oil", "butter"],
    "vegetable oil": ["canola oil", "olive oil", "coconut oil", "butter"],
    "canola oil": ["vegetable oil", "olive oil", "coconut oil", "butter"],
    "tahini": ["peanut butter", "almond butter", "sunflower seed butter", "cashew butter"],
    "peanut butter": ["almond butter", "cashew butter", "sunflower seed butter", "tahini"],
    "almond butter": ["peanut butter", "cashew butter", "sunflower seed butter", "tahini"],
    "cashew butter": ["peanut butter", "almond butter", "sunflower seed butter", "tahini"],
    "sunflower seed butter": ["peanut butter", "almond butter", "cashew butter", "tahini"],
    "ricotta cheese": ["cottage cheese", "cream cheese", "greek yogurt", "silken tofu"],
    "tofu": ["tempeh", "seitan", "chickpeas", "black beans"],
    "tempeh": ["tofu", "seitan", "chickpeas", "black beans"],
    "seitan": ["tofu", "tempeh", "chickpeas", "black beans"],
    "chickpeas": ["black beans", "white beans", "lentils", "kidney beans"],
    "black beans": ["chickpeas", "white beans", "lentils", "kidney beans"],
    "white beans": ["chickpeas", "black beans", "lentils", "kidney beans"],
    "lentils": ["chickpeas", "black beans", "white beans", "kidney beans"],
    "kidney beans": ["chickpeas", "black beans", "white beans", "lentils"],
    "quinoa": ["rice", "barley", "bulgur", "farro"],
    "barley": ["rice", "quinoa", "bulgur", "farro"],
    "bulgur": ["rice", "quinoa", "barley", "farro"],
    "farro": ["rice", "quinoa", "barley", "bulgur"],
    "cauliflower rice": ["rice", "quinoa", "barley", "bulgur"],
    "cornmeal": ["polenta", "semolina", "corn grits", "masa harina"],
    "polenta": ["cornmeal", "semolina", "corn grits", "masa harina"],
    "semolina": ["cornmeal", "polenta", "corn grits", "masa harina"],
    "corn grits": ["cornmeal", "polenta", "semolina", "masa harina"],
    "masa harina": ["cornmeal", "polenta", "semolina", "corn grits"],
    "arugula": ["spinach", "kale", "watercress", "mustard greens"],
    "spinach": ["arugula", "kale", "watercress", "mustard greens"],
    "kale": ["arugula", "spinach", "watercress", "mustard greens"],
    "watercress": ["arugula", "spinach", "kale", "mustard greens"],
    "mustard greens": ["arugula", "spinach", "kale", "watercress"],
    "zucchini": ["yellow squash", "cucumber", "eggplant", "bell pepper"],
    "yellow squash": ["zucchini", "cucumber", "eggplant", "bell pepper"],
    "cucumber": ["zucchini", "yellow squash", "eggplant", "bell pepper"],
    "eggplant": ["zucchini", "yellow squash", "cucumber", "bell pepper"],
    "bell pepper": ["zucchini", "yellow squash", "cucumber", "eggplant"],
    "carrot": ["parsnip", "sweet potato", "butternut squash", "pumpkin"],
    "parsnip": ["carrot", "sweet potato", "butternut squash", "pumpkin"],
    "sweet potato": ["carrot", "parsnip", "butternut squash", "pumpkin"],
    "butternut squash": ["carrot", "parsnip", "sweet potato", "pumpkin"],
    "pumpkin": ["carrot", "parsnip", "sweet potato", "butternut squash"],
    "broccoli": ["cauliflower", "brussels sprouts", "asparagus", "green beans"],
    "cauliflower": ["broccoli", "brussels sprouts", "asparagus", "green beans"],
    "brussels sprouts": ["broccoli", "cauliflower", "asparagus", "green beans"],
    "asparagus": ["broccoli", "cauliflower", "brussels sprouts", "green beans"],
    "green beans": ["broccoli", "cauliflower", "brussels sprouts", "asparagus"],
    "mushroom": ["eggplant", "zucchini", "bell pepper", "tofu"],
    "tofu": ["tempeh", "seitan", "chickpeas", "black beans"],
    "tempeh": ["tofu", "seitan", "chickpeas", "black beans"],
    "seitan": ["tofu", "tempeh", "chickpeas", "black beans"],
    "chickpeas": ["black beans", "white beans", "lentils", "kidney beans"],
    "black beans": ["chickpeas", "white beans", "lentils", "kidney beans"],
    "white beans": ["chickpeas", "black beans", "lentils", "kidney beans"],
    "lentils": ["chickpeas", "black beans", "white beans", "kidney beans"],
    "kidney beans": ["chickpeas", "black beans", "white beans", "lentils"],
    "quinoa": ["rice", "barley", "bulgur", "farro"],
    "barley": ["rice", "quinoa", "bulgur", "farro"],
    "bulgur": ["rice", "quinoa", "barley", "farro"],
    "farro": ["rice", "quinoa", "barley", "bulgur"],
    "cauliflower rice": ["rice", "quinoa", "barley", "bulgur"],
    "cornmeal": ["polenta", "semolina", "corn grits", "masa harina"],
    "polenta": ["cornmeal", "semolina", "corn grits", "masa harina"],
    "semolina": ["cornmeal", "polenta", "corn grits", "masa harina"],
    "corn grits": ["cornmeal", "polenta", "semolina", "masa harina"],
    "masa harina": ["cornmeal", "polenta", "semolina", "corn grits"],
    "arugula": ["spinach", "kale", "watercress", "mustard greens"],
    "spinach": ["arugula", "kale", "watercress", "mustard greens"],
    "kale": ["arugula", "spinach", "watercress", "mustard greens"],
    "watercress": ["arugula", "spinach", "kale", "mustard greens"],
    "mustard greens": ["arugula", "spinach", "kale", "watercress"],
    "zucchini": ["yellow squash", "cucumber", "eggplant", "bell pepper"],
    "yellow squash": ["zucchini", "cucumber", "eggplant", "bell pepper"],
    "cucumber": ["zucchini", "yellow squash", "eggplant", "bell pepper"],
    "eggplant": ["zucchini", "yellow squash", "cucumber", "bell pepper"],
    "bell pepper": ["zucchini", "yellow squash", "cucumber", "eggplant"],
    "carrot": ["parsnip", "sweet potato", "butternut squash", "pumpkin"],
    "parsnip": ["carrot", "sweet potato", "butternut squash", "pumpkin"],
    "sweet potato": ["carrot", "parsnip", "butternut squash", "pumpkin"],
    "butternut squash": ["carrot", "parsnip", "sweet potato", "pumpkin"],
    "pumpkin": ["carrot", "parsnip", "sweet potato", "butternut squash"],
    "broccoli": ["cauliflower", "brussels sprouts", "asparagus", "green beans"],
    "cauliflower": ["broccoli", "brussels sprouts", "asparagus", "green beans"],
    "brussels sprouts": ["broccoli", "cauliflower", "asparagus", "green beans"],
    "asparagus": ["broccoli", "cauliflower", "brussels sprouts", "green beans"],
    "green beans": ["broccoli", "cauliflower", "brussels sprouts", "asparagus"],
    "mushroom": ["eggplant", "zucchini", "bell pepper", "tofu"]
    // Add more static substitutions here as needed
  };
  
  export default staticSubstitutions;
  